[tool.poetry]
name = "plexport"
version = "1.0.0"
description = "plexport is a Python command-line tool that can perform ETL operations against a Plex Media Server instance."
license = "GPL-3.0-only"
authors = ["Antoine <achatain@users.noreply.github.com>"]
homepage = "https://bonjour.software"
repository = "https://github.com/bonjoursoftware/plexport"

[tool.poetry.dependencies]
pymongo = "4.6.0"
python = "^3.9"
requests = "2.31.0"

[tool.poetry.dev-dependencies]
black = "23.11.0"
flake8 = "6.1.0"
mongita = "1.2.0"
mypy = "1.7.0"
pytest = "7.4.3"
pytest-cov = "4.1.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
