[tool.poetry]
name = "plexport"
version = "1.0.0"
description = "plexport is a Python command-line tool that exports Plex Media Server database"
license = "GPL-3.0-only"
authors = ["Antoine <achatain@users.noreply.github.com>"]
homepage = "https://bonjour.software"
repository = "https://github.com/bonjoursoftware/plexport"

[tool.poetry.dependencies]
python = "^3.9"
requests = "2.26.0"

[tool.poetry.dev-dependencies]
black = "21.7b0"
flake8 = "3.9.2"
mypy = "0.910"
pytest = "6.2.4"
pytest-cov = "2.12.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
