[tool.poetry]
name = "plexport"
version = "1.0.0"
description = "plexport is a Python command-line tool that exports Plex Media Server database"
license = "GPL-3.0-only"
authors = ["Antoine <achatain@users.noreply.github.com>"]
homepage = "https://bonjour.software"
repository = "https://github.com/bonjoursoftware/plexport"

[tool.poetry.dependencies]
python = "^3.9"
requests = "2.31.0"

[tool.poetry.dev-dependencies]
black = "23.3.0"
flake8 = "6.0.0"
mypy = "1.3.0"
pytest = "7.3.1"
pytest-cov = "4.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
