[tool.poetry]
name = "plexport"
version = "1.0.0"
description = "plexport is a Python command-line tool that can perform ETL operations against a Plex Media Server instance."
license = "GPL-3.0-only"
authors = ["Antoine <achatain@users.noreply.github.com>"]
homepage = "https://bonjour.software"
repository = "https://github.com/bonjoursoftware/plexport"

[tool.poetry.dependencies]
pymongo = "4.13.0"
python = "^3.9"
requests = "2.32.4"

[tool.poetry.dev-dependencies]
black = "25.1.0"
flake8 = "7.2.0"
mongita = "1.2.0"
mypy = "1.16.0"
pytest = "8.4.0"
pytest-cov = "6.1.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
